Vagrant.configure("2")do|config|
  config.vm.box="centos/7"

  config.vbguest.auto_update = false
  config.vm.box_check_update = false 
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "node1" do |node1|
      node1.vm.hostname = "node1.tp4.b2"
      node1.vm.network "private_network", ip: "192.168.1.11", netmask:"255.255.255.0"
      node1.vm.provision :shell, path: "scripts/launch.sh"
      node1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
  end
end