Vagrant.configure("2")do|config|

  config.vm.box="centos/7"
  config.vbguest.auto_update = false
  config.vm.box_check_update = false 
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.hostname = "node"

  config.vm.define "tp2" do |tp2|
    tp2.vm.network "private_network", ip: "192.168.2.11", netmask:"255.255.255.0"
    tp2.vm.provider "virtualbox" do |vb|
      vb.name = "TP2 VM"
      vb.memory = "1024"
    end
  end
end